const temp_bans = {
    "29": {
        "id": 29,
        "name": "npc_dota_hero_tidehunter",
        "localized_name": "Tidehunter",
        "primary_attr": "str",
        "attack_type": "Melee",
        "roles": [
            "Initiator",
            "Durable",
            "Disabler",
            "Nuker",
            "Carry"
        ],
        "img": "/apps/dota2/images/heroes/tidehunter_full.png?",
        "icon": "/apps/dota2/images/heroes/tidehunter_icon.png",
        "base_health": 200,
        "base_health_regen": null,
        "base_mana": 75,
        "base_mana_regen": 0,
        "base_armor": 0,
        "base_mr": 25,
        "base_attack_min": 25,
        "base_attack_max": 31,
        "base_str": 27,
        "base_agi": 15,
        "base_int": 18,
        "str_gain": 3.5,
        "agi_gain": 1.5,
        "int_gain": 1.7,
        "attack_range": 150,
        "projectile_speed": 900,
        "attack_rate": 1.7,
        "move_speed": 300,
        "turn_rate": null,
        "cm_enabled": true,
        "legs": 2
    },
    "7": {
        "id": 7,
        "name": "npc_dota_hero_earthshaker",
        "localized_name": "Earthshaker",
        "primary_attr": "str",
        "attack_type": "Melee",
        "roles": [
            "Support",
            "Initiator",
            "Disabler",
            "Nuker"
        ],
        "img": "/apps/dota2/images/heroes/earthshaker_full.png?",
        "icon": "/apps/dota2/images/heroes/earthshaker_icon.png",
        "base_health": 200,
        "base_health_regen": 1,
        "base_mana": 75,
        "base_mana_regen": 0,
        "base_armor": 2,
        "base_mr": 25,
        "base_attack_min": 27,
        "base_attack_max": 37,
        "base_str": 22,
        "base_agi": 12,
        "base_int": 16,
        "str_gain": 3.7,
        "agi_gain": 1.4,
        "int_gain": 1.8,
        "attack_range": 150,
        "projectile_speed": 0,
        "attack_rate": 1.7,
        "move_speed": 310,
        "turn_rate": 0.9,
        "cm_enabled": true,
        "legs": 2
    },
    "8": {
        "id": 8,
        "name": "npc_dota_hero_juggernaut",
        "localized_name": "Juggernaut",
        "primary_attr": "agi",
        "attack_type": "Melee",
        "roles": [
            "Carry",
            "Pusher",
            "Escape"
        ],
        "img": "/apps/dota2/images/heroes/juggernaut_full.png?",
        "icon": "/apps/dota2/images/heroes/juggernaut_icon.png",
        "base_health": 200,
        "base_health_regen": 0.5,
        "base_mana": 75,
        "base_mana_regen": 0,
        "base_armor": 0,
        "base_mr": 25,
        "base_attack_min": 16,
        "base_attack_max": 20,
        "base_str": 20,
        "base_agi": 34,
        "base_int": 14,
        "str_gain": 2.2,
        "agi_gain": 2.8,
        "int_gain": 1.4,
        "attack_range": 150,
        "projectile_speed": 0,
        "attack_rate": 1.4,
        "move_speed": 305,
        "turn_rate": null,
        "cm_enabled": true,
        "legs": 2
    },
    "9": {
        "id": 9,
        "name": "npc_dota_hero_mirana",
        "localized_name": "Mirana",
        "primary_attr": "agi",
        "attack_type": "Ranged",
        "roles": [
            "Carry",
            "Support",
            "Escape",
            "Nuker",
            "Disabler"
        ],
        "img": "/apps/dota2/images/heroes/mirana_full.png?",
        "icon": "/apps/dota2/images/heroes/mirana_icon.png",
        "base_health": 200,
        "base_health_regen": null,
        "base_mana": 75,
        "base_mana_regen": 0.4,
        "base_armor": -1,
        "base_mr": 25,
        "base_attack_min": 27,
        "base_attack_max": 32,
        "base_str": 18,
        "base_agi": 18,
        "base_int": 22,
        "str_gain": 2.2,
        "agi_gain": 3.7,
        "int_gain": 1.9,
        "attack_range": 630,
        "projectile_speed": 900,
        "attack_rate": 1.7,
        "move_speed": 290,
        "turn_rate": null,
        "cm_enabled": true,
        "legs": 2
    },
    "10": {
        "id": 10,
        "name": "npc_dota_hero_morphling",
        "localized_name": "Morphling",
        "primary_attr": "agi",
        "attack_type": "Ranged",
        "roles": [
            "Carry",
            "Escape",
            "Durable",
            "Nuker",
            "Disabler"
        ],
        "img": "/apps/dota2/images/heroes/morphling_full.png?",
        "icon": "/apps/dota2/images/heroes/morphling_icon.png",
        "base_health": 200,
        "base_health_regen": null,
        "base_mana": 75,
        "base_mana_regen": 0,
        "base_armor": -2,
        "base_mr": 25,
        "base_attack_min": 9,
        "base_attack_max": 18,
        "base_str": 22,
        "base_agi": 24,
        "base_int": 19,
        "str_gain": 3,
        "agi_gain": 4.3,
        "int_gain": 1.8,
        "attack_range": 350,
        "projectile_speed": 1300,
        "attack_rate": 1.5,
        "move_speed": 280,
        "turn_rate": null,
        "cm_enabled": true,
        "legs": 0
    },
    "11": {
        "id": 11,
        "name": "npc_dota_hero_nevermore",
        "localized_name": "Shadow Fiend",
        "primary_attr": "agi",
        "attack_type": "Ranged",
        "roles": [
            "Carry",
            "Nuker"
        ],
        "img": "/apps/dota2/images/heroes/nevermore_full.png?",
        "icon": "/apps/dota2/images/heroes/nevermore_icon.png",
        "base_health": 200,
        "base_health_regen": 0.25,
        "base_mana": 75,
        "base_mana_regen": 0.3,
        "base_armor": 1,
        "base_mr": 25,
        "base_attack_min": 19,
        "base_attack_max": 25,
        "base_str": 19,
        "base_agi": 20,
        "base_int": 18,
        "str_gain": 2.7,
        "agi_gain": 3.5,
        "int_gain": 2.2,
        "attack_range": 500,
        "projectile_speed": 1200,
        "attack_rate": 1.6,
        "move_speed": 305,
        "turn_rate": 0.9,
        "cm_enabled": true,
        "legs": 0
    },
    "12": {
        "id": 12,
        "name": "npc_dota_hero_phantom_lancer",
        "localized_name": "Phantom Lancer",
        "primary_attr": "agi",
        "attack_type": "Melee",
        "roles": [
            "Carry",
            "Escape",
            "Pusher",
            "Nuker"
        ],
        "img": "/apps/dota2/images/heroes/phantom_lancer_full.png?",
        "icon": "/apps/dota2/images/heroes/phantom_lancer_icon.png",
        "base_health": 200,
        "base_health_regen": 1.5,
        "base_mana": 75,
        "base_mana_regen": 0,
        "base_armor": 0,
        "base_mr": 25,
        "base_attack_min": 28,
        "base_attack_max": 38,
        "base_str": 19,
        "base_agi": 26,
        "base_int": 21,
        "str_gain": 2.2,
        "agi_gain": 3.2,
        "int_gain": 2,
        "attack_range": 150,
        "projectile_speed": 900,
        "attack_rate": 1.7,
        "move_speed": 290,
        "turn_rate": null,
        "cm_enabled": true,
        "legs": 2
    }
}

export default temp_bans;