const temp_picks = {
    "1": {
        "id": 1,
        "name": "npc_dota_hero_antimage",
        "localized_name": "Anti-Mage",
        "primary_attr": "agi",
        "attack_type": "Melee",
        "roles": [
            "Carry",
            "Escape",
            "Nuker"
        ],
        "img": "/apps/dota2/images/heroes/antimage_full.png?",
        "icon": "/apps/dota2/images/heroes/antimage_icon.png",
        "base_health": 200,
        "base_health_regen": 0.25,
        "base_mana": 75,
        "base_mana_regen": 0,
        "base_armor": -1,
        "base_mr": 25,
        "base_attack_min": 29,
        "base_attack_max": 33,
        "base_str": 23,
        "base_agi": 24,
        "base_int": 12,
        "str_gain": 1.3,
        "agi_gain": 2.8,
        "int_gain": 1.8,
        "attack_range": 150,
        "projectile_speed": 0,
        "attack_rate": 1.4,
        "move_speed": 310,
        "turn_rate": null,
        "cm_enabled": true,
        "legs": 2
    },
    "2": {
        "id": 2,
        "name": "npc_dota_hero_axe",
        "localized_name": "Axe",
        "primary_attr": "str",
        "attack_type": "Melee",
        "roles": [
            "Initiator",
            "Durable",
            "Disabler",
            "Jungler",
            "Carry"
        ],
        "img": "/apps/dota2/images/heroes/axe_full.png?",
        "icon": "/apps/dota2/images/heroes/axe_icon.png",
        "base_health": 200,
        "base_health_regen": 2.75,
        "base_mana": 75,
        "base_mana_regen": 0,
        "base_armor": -1,
        "base_mr": 25,
        "base_attack_min": 27,
        "base_attack_max": 31,
        "base_str": 25,
        "base_agi": 20,
        "base_int": 18,
        "str_gain": 3.4,
        "agi_gain": 2.2,
        "int_gain": 1.6,
        "attack_range": 150,
        "projectile_speed": 900,
        "attack_rate": 1.7,
        "move_speed": 310,
        "turn_rate": null,
        "cm_enabled": true,
        "legs": 2
    },
    "3": {
        "id": 3,
        "name": "npc_dota_hero_bane",
        "localized_name": "Bane",
        "primary_attr": "int",
        "attack_type": "Ranged",
        "roles": [
            "Support",
            "Disabler",
            "Nuker",
            "Durable"
        ],
        "img": "/apps/dota2/images/heroes/bane_full.png?",
        "icon": "/apps/dota2/images/heroes/bane_icon.png",
        "base_health": 200,
        "base_health_regen": null,
        "base_mana": 75,
        "base_mana_regen": 0,
        "base_armor": 1,
        "base_mr": 25,
        "base_attack_min": 35,
        "base_attack_max": 41,
        "base_str": 22,
        "base_agi": 22,
        "base_int": 22,
        "str_gain": 2.6,
        "agi_gain": 2.6,
        "int_gain": 2.6,
        "attack_range": 400,
        "projectile_speed": 900,
        "attack_rate": 1.7,
        "move_speed": 305,
        "turn_rate": null,
        "cm_enabled": true,
        "legs": 4
    },
    "4": {
        "id": 4,
        "name": "npc_dota_hero_bloodseeker",
        "localized_name": "Bloodseeker",
        "primary_attr": "agi",
        "attack_type": "Melee",
        "roles": [
            "Carry",
            "Disabler",
            "Jungler",
            "Nuker",
            "Initiator"
        ],
        "img": "/apps/dota2/images/heroes/bloodseeker_full.png?",
        "icon": "/apps/dota2/images/heroes/bloodseeker_icon.png",
        "base_health": 200,
        "base_health_regen": null,
        "base_mana": 75,
        "base_mana_regen": 0,
        "base_armor": 2,
        "base_mr": 25,
        "base_attack_min": 35,
        "base_attack_max": 41,
        "base_str": 24,
        "base_agi": 22,
        "base_int": 17,
        "str_gain": 2.7,
        "agi_gain": 3.4,
        "int_gain": 2,
        "attack_range": 150,
        "projectile_speed": 900,
        "attack_rate": 1.7,
        "move_speed": 300,
        "turn_rate": null,
        "cm_enabled": true,
        "legs": 2
    },
    "5": {
        "id": 5,
        "name": "npc_dota_hero_crystal_maiden",
        "localized_name": "Crystal Maiden",
        "primary_attr": "int",
        "attack_type": "Ranged",
        "roles": [
            "Support",
            "Disabler",
            "Nuker",
            "Jungler"
        ],
        "img": "/apps/dota2/images/heroes/crystal_maiden_full.png?",
        "icon": "/apps/dota2/images/heroes/crystal_maiden_icon.png",
        "base_health": 200,
        "base_health_regen": null,
        "base_mana": 75,
        "base_mana_regen": 1,
        "base_armor": -1,
        "base_mr": 25,
        "base_attack_min": 28,
        "base_attack_max": 34,
        "base_str": 18,
        "base_agi": 16,
        "base_int": 16,
        "str_gain": 2.2,
        "agi_gain": 1.6,
        "int_gain": 3.3,
        "attack_range": 600,
        "projectile_speed": 900,
        "attack_rate": 1.7,
        "move_speed": 280,
        "turn_rate": null,
        "cm_enabled": true,
        "legs": 2
    }
}

export default temp_picks;